shell zsh

# Minimal Tab bar styling 
tab_bar_edge                bottom
tab_bar_style               powerline
tab_powerline_style         slanted
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}

# remap to open new kitty tab in the same directory (default is home dir)
# map ctrl+shift+t            new_tab_with_cwd

# Uncomment the following 4 lines to minimize kitty latency (higher energy usage)
# input_delay 0
# repaint_delay 2
sync_to_monitor no
wayland_enable_ime no

# custom overrides
font_family Noto Sans Font
font_size 12

window_padding_width 4
window_padding_height 4

map ctrl+backspace send_text all \x1b\x7f

cursor_shape block
cursor_trail 3
cursor_trail_decay 0.1 0.4

background_opacity 0.6
shell_integration no-cursor

# BEGIN_KITTY_THEME
# Noctalia
include current-theme.conf
# END_KITTY_THEME