color0 #10132d
color1 #fd4663
color2 #6772e4
color3 #8f5cd6
color4 #c366cc
color5 #939bec
color6 #b896e9
color7 #f2f2f3
color8 #606174
color9 #fd4663
color10 #6772e4
color11 #8f5cd6
color12 #c366cc
color13 #939bec
color14 #b896e9
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #10132d
background            #10132d
foreground            #f2f2f3
selection_foreground  #afafb6
selection_background  #16193c
active_border_color   #6772e4
inactive_border_color #16193c
url_color             #6772e4
