$primary = rgb(7a88cf)
$surface = rgb(1f2335)
$secondary = rgb(d7729f)
$error = rgb(f7768e)
$tertiary = rgb(9cd58a)
$surface_lowest = rgb(1f2335)

general {
    col.active_border = $primary
    col.inactive_border = $surface
}

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
    }
}
